// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bus": {
    params: {};
  };
  "/weather": {
    params: {};
  };
  "/vaskeliste": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/bus" | "/weather" | "/vaskeliste";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/bus" | "/weather" | "/vaskeliste";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/bus.tsx": {
    id: "routes/bus";
    page: "/bus";
  };
  "routes/weather.tsx": {
    id: "routes/weather";
    page: "/weather";
  };
  "routes/vaskeliste.tsx": {
    id: "routes/vaskeliste";
    page: "/vaskeliste";
  };
};